name: smart_ahwa
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  lottie: ^3.3.1
  riverpod: ^3.0.0
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.7
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
